/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2020  wugang <wugang@uniontech.com>
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface dde_shell_surface_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *dde_shell_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&dde_shell_surface_interface,
	&wl_surface_interface,
	&wl_output_interface,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message dde_shell_requests[] = {
	{ "get_shell_surface", "no", dde_shell_types + 4 },
};

WL_PRIVATE const struct wl_interface dde_shell_interface = {
	"dde_shell", 2,
	1, dde_shell_requests,
	0, NULL,
};

static const struct wl_message dde_shell_surface_requests[] = {
	{ "get_geometry", "", dde_shell_types + 0 },
	{ "request_active", "", dde_shell_types + 0 },
	{ "set_state", "uu", dde_shell_types + 0 },
	{ "set_property", "2ua", dde_shell_types + 0 },
	{ "request_split_window", "u", dde_shell_types + 0 },
	{ "request_window_effect", "2u", dde_shell_types + 0 },
	{ "request_window_startup_effect", "2u", dde_shell_types + 0 },
};

static const struct wl_message dde_shell_surface_events[] = {
	{ "geometry", "iiuu", dde_shell_types + 0 },
	{ "state_changed", "u", dde_shell_types + 0 },
	{ "splitable", "u", dde_shell_types + 0 },
	{ "workarea", "2ouuuu", dde_shell_types + 6 },
};

WL_PRIVATE const struct wl_interface dde_shell_surface_interface = {
	"dde_shell_surface", 2,
	7, dde_shell_surface_requests,
	4, dde_shell_surface_events,
};

